weights: yolov9-c.pt
cfg: /home/user/Desktop/shikharvashistha/CarlaFLCAV/FLYolo/yolov9/models/detect/yolov9-c.yaml
data: /home/user/Desktop/shikharvashistha/CarlaFLCAV/FLYolo/yolov9/raw_data
hyp: /home/user/Desktop/shikharvashistha/CarlaFLCAV/FLYolo/yolov9/data/hyps/hyp.scratch-high.yaml
epochs: 50
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noplots: false
spsz: 1000
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: yolov9/runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save: ''
min_items: 10
save_dir: yolov9/runs/train/exp
